#                                                 ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥
#                                                   ğŸ’»Phoenix Buckets ConfigğŸ’»
#                                                   ğŸ”¥Coded By Mike3132ğŸ”¥
#                                                   ğŸ’»Phoenix Buckets ConfigğŸ’»
#                                                 ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥

Version: 'Version 1.0'
ConfigVersion: '1.0'
##### WARNING: DO NOT CHANGE ANYTHING ABOVE THIS LINE IT WILL BREAK THE PLUGIN!#####

#âœâœâœâœâœPermissionsâœâœâœâœâœ
#PhoenixBuckets.Command > Access to /InfiniteBuckets command
#PhoenixBuckets.Reload > Access to reload the plugin configs and messages files
#PhoenixBuckets.Give > Access to giving InfiniteBuckets
#âœâœâœâœâœPermissionsâœâœâœâœâœ


#####You can Modify the following how you wish#####
#â™¢â™¢â™¢â™¢â™¢Water Bucket Itemâ™¢â™¢â™¢â™¢â™¢

#Water Bucket name -> Name of the ender pearl (Please use & for color codes).
Water-Bucket-Name: '&bInfinite Water Bucket'

#Water Bucket lore -> Any lore lines you would like on the ender pearl (Please use & for color codes).
Water-Bucket-Lore:
  - '&5This is an infinite water bucket'
  - '&dIt will never run out'

#Lava Bucket name -> Name of the ender pearl (Please use & for color codes).
Lava-Bucket-Name: '&4Infinite Lava Bucket'

#Lava Bucket lore -> Any lore lines you would like on the ender pearl (Please use & for color codes).
Lava-Bucket-Lore:
  - '&6This is an infinite lava bucket'
  - '&eIt will never run out'

#See messages.yml for all configurable plugin messages
#â™ If you have any questions please join my discord, open a support ticket and @Mike3132
#â™ https://discord.gg/EHm6Ra3K
#â™ Thanks for downloading and have a wonderful day

#â™›â™›â™›â™›â™› END OF CONFIG â™›â™›â™›â™›â™›
#This is the default file.
